apiVersion: apps/v1
kind: Deployment
metadata:
  name: metasfresh-ui
  namespace: {{ .Values.global.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "40"
spec:
  replicas: {{ .Values.ui.replicaCount }}
  selector:
    matchLabels:
      app: metasfresh-ui
  template:
    metadata:
      labels:
        app: metasfresh-ui
    spec:
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.global.imagePullSecrets | nindent 8 }}
      {{- end }}
      nodeSelector:
        {{- toYaml .Values.ui.nodeSelector | nindent 8 }}
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: metasfresh-ui
      containers:
        - name: ui
          image: "{{ .Values.ui.image.repository }}{{ if .Values.ui.image.digest }}@{{ .Values.ui.image.digest }}{{ else }}:{{ .Values.ui.image.tag }}{{ end }}"
          imagePullPolicy: {{ .Values.ui.image.pullPolicy }}
          resources:
            {{- toYaml .Values.ui.resources | nindent 12 }}
          env:
            - name: API_URL
              value: "https://{{ .Values.ingress.host }}/rest/api"
            - name: WS_URL
              value: "https://{{ .Values.ingress.host }}/stomp"
