apiVersion: apps/v1
kind: Deployment
metadata:
  name: metasfresh-core
  namespace: {{ .Values.global.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  replicas: {{ .Values.core.replicaCount }}
  selector:
    matchLabels:
      app: metasfresh-core
  template:
    metadata:
      labels:
        app: metasfresh-core
    spec:
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.global.imagePullSecrets | nindent 8 }}
      {{- end }}
      nodeSelector:
        {{- toYaml .Values.core.nodeSelector | nindent 8 }}
      containers:
        - name: core
          image: "{{ .Values.core.image.repository }}:{{ .Values.core.image.tag }}"
          imagePullPolicy: {{ .Values.core.image.pullPolicy }}
          resources:
            {{- toYaml .Values.core.resources | nindent 12 }}
          env:
            - name: DB_HOST
              value: "{{ .Values.externalDB.pgHost }}"
            - name: DB_PORT
              value: "{{ .Values.externalDB.pgPort }}"
            - name: RABBITMQ_HOST
              value: "{{ .Values.externalDB.rabbitHost }}"
            - name: RABBITMQ_PORT
              value: "{{ .Values.externalDB.rabbitPort }}"
            - name: ES_HOST
              value: "{{ .Values.externalDB.searchHost }}"
            - name: ES_PORT
              value: "{{ .Values.externalDB.searchPort }}"
          # TODO: Mount secret 'erp-properties' if required by the image
          volumeMounts:
            - name: business-data
              mountPath: /opt/metasfresh/data
      volumes:
        - name: business-data
          persistentVolumeClaim:
            claimName: core-business-pvc
