apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: core-business-pvc
  namespace: {{ .Values.global.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "10"
    # Ngăn chặn xóa tự động trong ArgoCD
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
