apiVersion: v1
kind: Service
metadata:
  name: metasfresh-core
  namespace: {{ include "erp.namespace" . }}
  labels:
    app: metasfresh-core
    {{- include "erp.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  type: ClusterIP
  selector: {app: metasfresh-core}
  ports:
    - name: http
      protocol: TCP
      port: 8282
      targetPort: http
