apiVersion: v1
kind: Service
metadata:
  name: metasfresh-core
  namespace: {{ .Values.global.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  selector:
    app: metasfresh-core
  ports:
    - protocol: TCP
      port: 8282
      targetPort: 8282
