apiVersion: v1
kind: Service
metadata:
  name: metasfresh-ui
  namespace: {{ .Values.global.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  selector:
    app: metasfresh-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
