apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metasfresh-erp-secrets
  namespace: argocd
spec:
  project: erp
  source:
    repoURL: https://github.com/hoi3dkhoiche-byte/GitOps-final-lab.git
    targetRevision: main
    path: sealed-secrets/erp
    directory:
      recurse: true
      include: "*.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: erp
  syncPolicy: {}
