apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metasfresh-erp
  namespace: argocd
spec:
  project: erp
  source:
    repoURL: 'YOUR_GIT_REPO_URL' # Thay bằng URL repo gitops thực tế
    path: charts/erp-adapter
    targetRevision: HEAD
    helm:
      valueFiles:
        - ../../environments/lab/values-lab.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: erp
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      name: metasfresh-ui
      jsonPointers:
        - /spec/replicas
